version: "3.9"
services:
  postgres_db:
    image: postgres
    restart: always
    command: -p 5433
    env_file:
      - web/.env
    expose:
      - 5433
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
